/**
 * Replace the vowel in a string with a character,
 * for example '*', or another string
 *
 * @param word - The original string
 * @param charToReplaceVowels - The character or string to replace the vowels
 * @returns The string with vowels replaced by the character or string
 *
 */
export function replaceVowels( word: string, charToReplaceVowels: string ): string {

    return word.replace(/a|á|à|â|ã|e|é|è|ê|i|í|o|ó|ô|u|ú/gi, charToReplaceVowels);
}

// PONTUACTION CHARACTERS AT THE END
const pontuationCharacters:string = '.!?,';
export function pontuationCharacterAtTheEnd( text: string ):boolean {
    return pontuationCharacters.includes(
        text[text.length-1]
    );
}

// PONTUACTION CHARACTERS AT THE START
export function pontuationCharacterAtTheStart( text: string ): boolean {
    return pontuationCharacters.includes(text[0]);
}

// REVERSE WORD
export function reverseWord( wordToReverse: string ): string {
    let lastCharacter= '';
    if (pontuationCharacterAtTheEnd( wordToReverse )) {
        lastCharacter = wordToReverse[wordToReverse.length-1];
        wordToReverse = wordToReverse.substring(0, wordToReverse.length-1);
    }
    return wordToReverse.split('').reverse().join('') + lastCharacter;
}

export function reverseAllWords(text: string): string {
    let textWithAllReversedWords = "";
    let words = text.split(/\s/gi);
    words.forEach((word) => {
        textWithAllReversedWords += reverseWord(word) + " ";
    })
    return textWithAllReversedWords.trimEnd();
}

// SHUFFLE WORD
export function shuffleWord( word: string ): string {

    if (word.length === 1) return word;
    if (word.length === 2) return reverseWord(word);

    let lastCharacter = '';

    if (pontuationCharacterAtTheEnd( word )) {
        lastCharacter = word[word.length-1];
        word = word.substring(0, word.length-1);
    }

    const originalWord  = word;
    let shuffledWord    = word.split('').sort(() => Math.random() - 0.5).join('');
    if (shuffledWord === word) {
        shuffledWord    = word.split('').sort(() => Math.random() - 0.5).join('');
    }
    if (shuffledWord === word) {
        shuffledWord    = word.split('').sort(() => Math.random() - 0.5).join('');
    }
    if (shuffledWord === word) {
        shuffledWord    = word.split('').sort(() => Math.random() - 0.5).join('');
    }

    shuffledWord += lastCharacter;

    return shuffledWord;
}

export function shuffledWordsText(originalText: string): string {
    const words = originalText.split(/\s/g);
    let shuffledWordsText = "";
    words.forEach( (word) => {
        let shuffledWord = shuffleWord(word);
        shuffledWordsText += shuffledWord + " ";
    })
    return shuffledWordsText.trimEnd();
}


// LETTERS TO NUMBERS
export function lettersToNumbers( upperCasedWord: string ): string {

    let changedWord = upperCasedWord;
    changedWord = 
        changedWord
        .replace(/A|Á|À|Â|Ã/gi, '4')
        .replace(/E|É|È/gi, '3')
        .replace(/I|Í|Ì/gi, '1')
        .replace(/O|Ó|Ò/gi, '0')
        .replace(/S/gi, '5')
        .replace(/G/gi, '6')
        .replace(/T/gi, '7');
    return changedWord;
}

// TEXT TO ASCII LETTERS AND SPACE ONLY
export function asciiLettersAndSpaceCharsOnly(stringToEncript: string): string {
    let onlyAsciiLettersMessage = '';

    onlyAsciiLettersMessage =
        stringToEncript
        .replace(/á|à|â|ã/gi, 'a')
        .replace(/é|è|ê/gi, 'e')
        .replace(/í|ì/gi, 'i')
        .replace(/ó|ò|ô/gi, 'o')
        .replace(/ú/gi, 'u')
        .replace(/ç/gi, 'c')
        .replace(/-/gi, ' ')
        .replace(/[^A-Za-z]/gi, ' ')
        .replace(/\s\s/gi, ' ')
        .trim();

    return onlyAsciiLettersMessage;
}

// LETTER TO NATO ALPHABETH LETTER
export function translateLetterToNATOAlphabet( letter: string ): string {

    const translationObject = {
        a: 'Alpha',
        b: 'Bravo',
        c: 'Charlie',
        d: 'Delta',
        e: 'Echo',
        f: 'Foxtrot',
        g: 'Golf',
        h: 'Hotel',
        i: 'India',
        j: 'Juliet',
        k: 'Kilo',
        l: 'Lima',
        m: 'Mike',
        n: 'November',
        o: 'Oscar',
        p: 'Papa',
        q: 'Quebec	',
        r: 'Romeo',
        s: 'Sierra',
        t: 'Tango',
        u: 'Uniform',
        v: 'Victor',
        w: 'Whiskey',
        x: 'X-Ray',
        y: 'Yankee',
        z: 'Zulu'
    };

    const keyLetter = letter[0].toUpperCase();

    const wordsArray = Object.values(translationObject);
    for (let i = 0; i < wordsArray.length; i++) {
        if (wordsArray[i].startsWith(keyLetter)) {
            return wordsArray[i];
        }
    }
    return "";
}

// WORD TO NATO ALPHABETH
export function translateLetterToNATOAlphabetFullText( originalText: string): string {
    const simplefiedText = asciiLettersAndSpaceCharsOnly(originalText);

    let fullText = '';
    let words = simplefiedText.split(' ');
    const wordsLength  = words.length;

    for (let i = 0; i < wordsLength; i++) {
        const eachWord = words[i];
        eachWord.split("").forEach( (letter: string) => {
            fullText += translateLetterToNATOAlphabet(letter) + '\n';
        });

        fullText += '\n';
    }

    return fullText;
}

export function asciiLettersWordToLetterPositionsInAlphabeth( word: string): string {
    const alphabeth = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const wordLength = word.length;

    let postionsStr = "";

    for (let i = 0; i < wordLength; i++ ) {
        postionsStr += alphabeth.indexOf(word[i]) + 1;

        if (i < (wordLength-1) ) {
            postionsStr += '-';
        }


    }

    return postionsStr;
}

export function asciiLettersWordToLetterPositionsInAlphabethFullText( originalText: string): string {

    const key = 'A --> 1\nB --> 2\n   ...\nZ --> 26';
    const simplefiedText = asciiLettersAndSpaceCharsOnly(originalText);

    let fullText = key + '\n\n';

    simplefiedText.split(" ").forEach( (word) => {
        fullText += asciiLettersWordToLetterPositionsInAlphabeth(word) + '\n'
    });


    return simplefiedText ? fullText : "";
}

export function randomIntegerBetweenXandY(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min) ) + min;
}

const generateRandomString = (lengthOfGeneratedRandomString: number, lowerCased: boolean = true): string => {
    const upperCaseAlphabeth = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowerCaseAlphabeth = upperCaseAlphabeth.toLowerCase();

    let randomString = "";
    for (let i = 0; i < lengthOfGeneratedRandomString - 1; i++) {
        lowerCased ?
            randomString += lowerCaseAlphabeth[randomIntegerBetweenXandY(0, 26)]
            :
            randomString += upperCaseAlphabeth[randomIntegerBetweenXandY(0, 26)];
    }
    return randomString;
}

const simplifiedPhraseIntoHiddenCharactersByLine = ( simplifiedString: string, numberOfCharsByLine: number = 10, spacesBetween: boolean = true): string => {
   
    const words = simplifiedString.split(" ");
    let finalString = '';
    words.forEach( (word) => {
        let blockOfWordHiddenChars = '';
        word.split('').forEach( (char) => {
        const randomPositionOfChar = randomIntegerBetweenXandY(0, numberOfCharsByLine - 1);
        let placeHolderWord = generateRandomString(10);
        let tempWordArray = placeHolderWord.split('');
        tempWordArray[randomPositionOfChar] = char;
        let hiddenCharWord = tempWordArray.join('');
        blockOfWordHiddenChars += hiddenCharWord + '\n';
        })

        finalString += blockOfWordHiddenChars + (spacesBetween ? '\n' : '');


    });
    return finalString;
}

export function wordToWordPuzzleRow( asciiLettersWord: string, numberOfLettersInTheRow: number): string {
    const alphabeth = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lastIndexWereWordCanStart = numberOfLettersInTheRow - asciiLettersWord.length;
    const numberOfPostionsToFillInRow = lastIndexWereWordCanStart;
    const numberOfLettersBeforeWord = randomIntegerBetweenXandY(0, numberOfPostionsToFillInRow);
    const numberOfLettersAfterWord = numberOfPostionsToFillInRow - numberOfLettersBeforeWord;

    let wordWithLettersBeforeAndAfter = "";
    for (let i = 1; i <= numberOfLettersBeforeWord; i++ ) {
        const indexOfRandomLetter = randomIntegerBetweenXandY(0, 25);
        wordWithLettersBeforeAndAfter += alphabeth[indexOfRandomLetter];
    }

    wordWithLettersBeforeAndAfter += asciiLettersWord;

    for (let i = 1; i <= numberOfLettersAfterWord; i++ ) {
        const indexOfRandomLetter = randomIntegerBetweenXandY(0, 25);
        wordWithLettersBeforeAndAfter += alphabeth[indexOfRandomLetter];
    }


    return wordWithLettersBeforeAndAfter;
}

export function textToWordPuzzle(originalText: string, numberOfPaddingLetters: number): string {

    const simplefiedText = asciiLettersAndSpaceCharsOnly(originalText);
    const words = simplefiedText.split(' ');
    const lengthOfBiggestWord = Math.max(...words.map((word) => word.length));

    let wordPuzzleFullText = '';
    const lengthOfRow = lengthOfBiggestWord + numberOfPaddingLetters;

    words.forEach((word) => {
        wordPuzzleFullText += wordToWordPuzzleRow(word, lengthOfRow) + '\n'
    });


    return simplefiedText ? wordPuzzleFullText.toUpperCase() : "";
}

export const simplifiedPhraseIntoHiddenCharactersByLine2 = ( simplifiedString: string, numberOfCharsByLine: number): string => {
   
    const words = simplifiedString.split(" ");
    let finalString = '';
    words.forEach( (word) => {
      let blockOfWordHiddenChars = '';
      word.split('').forEach( (char) => {
        const randomPositionOfChar = Math.floor(Math.random() * (numberOfCharsByLine - 0) ) + 0;
        const lowerCasedAlphabeth = "abcdefghijklmnopqrstuvwxyz";
        let placeHolderWord = shuffleWord(lowerCasedAlphabeth);
        let tempWordArray = placeHolderWord.split('');
        tempWordArray[randomPositionOfChar] = char;
        let hiddenCharWord = tempWordArray.join('');
        blockOfWordHiddenChars += hiddenCharWord + '\n';
      })


      finalString += blockOfWordHiddenChars + '\n';


    });
    return finalString;
  }


  export const simplifiedPhraseIntoHiddenCharactersByLineSimpler = ( simplifiedString: string, numberOfCharsByLine: number): string => {
   
    const words = simplifiedString.split(" ");
    let finalString = '';
    words.forEach( (word) => {
      let blockOfWordHiddenChars = '';
      word.split('').forEach( (char) => {
        const randomPositionOfChar = Math.floor(Math.random() * (numberOfCharsByLine - 0) ) + 0;
        const lowerCasedConsoants = "bcdfghjklmnpqrstvwxyz";
        const lowerCasedVowels = "aeiouaeiouaeiouaeiou";
        let placeHolderWord = "";
        if (lowerCasedConsoants.indexOf(char.toLowerCase()) >= 0) {
            placeHolderWord = shuffleWord(lowerCasedVowels);
        }
        if (lowerCasedVowels.indexOf(char.toLowerCase()) >= 0) {
            placeHolderWord = shuffleWord(lowerCasedConsoants);
        }
        
        let tempWordArray = placeHolderWord.split('');
        tempWordArray[randomPositionOfChar] = char;
        let hiddenCharWord = tempWordArray.join('');
        blockOfWordHiddenChars += hiddenCharWord + '\n';
      })


      finalString += blockOfWordHiddenChars + '\n';


    });
    return finalString;
  }



export function initializeCellPhoneStr(): string {

    const cellPhoneStr = `
<pre>
<code>
 ________________
|                |
|                |
|                |
|                |
|                |
|    SMS 4 U     |
|                |
|                |
|                |
|                |
|                |
 ________________ 
|1    |2abc|3def |
|4ghi |5jkl|6mno |
|7pqrs|8tuv|9wxyz|
|*    |0   |#    |
 ________________
</code>
</pre>
<pre id="encrypted"></pre>`;

    return cellPhoneStr;
}


export function retroCellphoneEncription( stringToEncript: string ): string {

    const letters = 'abcdefghijklmnopqrstuvwxyz ';

    const abc2  = '2abc';
    const def3  = '3def';
    const ghi4  = '4ghi';
    const jkl5  = '5jkl';
    const mno6  = '6mno';
    const pqrs7 = '7pqrs';
    const tuv8  = '8tuv';
    const wxyz9 = '9wxyz';
    const _0    = '0 ';

    let encriptedString = "";

    stringToEncript.toLowerCase().split('').forEach( (char) => {
        let key = ''
        let numberOfKeyPresses = 0;
        if ( letters.includes(char) ) {
            if (abc2.includes(char) ) { key = abc2[0]; numberOfKeyPresses = abc2.indexOf(char) }
            if (def3.includes(char) ) { key = def3[0]; numberOfKeyPresses = def3.indexOf(char) }
            if (ghi4.includes(char) ) { key = ghi4[0]; numberOfKeyPresses = ghi4.indexOf(char) }
            if (jkl5.includes(char) ) { key = jkl5[0]; numberOfKeyPresses = jkl5.indexOf(char) }
            if (mno6.includes(char) ) { key = mno6[0]; numberOfKeyPresses = mno6.indexOf(char) }
            if (pqrs7.includes(char)) { key = pqrs7[0]; numberOfKeyPresses = pqrs7.indexOf(char) }
            if (tuv8.includes(char) ) { key = tuv8[0]; numberOfKeyPresses = tuv8.indexOf(char) }
            if (wxyz9.includes(char)) { key = wxyz9[0]; numberOfKeyPresses = wxyz9.indexOf(char) }
        }
        

        for (let i = 1; i <= numberOfKeyPresses; i++) {
            encriptedString += key
        }

        if (char !== ' ') {
            encriptedString += '-';
        } else {
            encriptedString = encriptedString.substring(0, encriptedString.length-1);
            encriptedString += ' ';
        }
        

    });

    encriptedString = encriptedString.substring(0, encriptedString.length-1);

    return encriptedString;

}


// VOWELS TO AIX ENDER INIX OVER UFUX
export function aixToUfux( word:string ): string {

    const key = 'A --> AIX \ta --> aix\nE --> ENDER \te --> ender\nI --> INIX \ti --> inix\nO --> OVER \to --> over\nU --> UFUX \tu --> ufux\n\n';

    let changedWord = '';

    for ( let i = 0; i < word.length; i++) {
        switch(word[i]) {

            case 'a':
            case 'á':
            case 'à':
            case 'â':
            case 'ã':
            changedWord += 'aix';
                break;
            case 'A':
            case 'Á':
            case 'À':
            case 'Â':
            case 'Ã':
            changedWord += 'AIX';
                break;
            
            case 'e':
            case 'é':
            case 'è':
            changedWord += 'ender';
                break;
            case 'E':
            case 'É':
            case 'È':
            changedWord += 'ENDER';
                break;
            
            case 'i':
            case 'í':
            case 'ì':
            changedWord += 'inix';
                break;
            case 'I':
            case 'Í':
            case 'Ì':
            changedWord += 'INIX';
                break;
            
            case 'o':
            case 'ó':
            case 'ò':
            changedWord += 'over';
                break;
            case 'O':
            case 'Ó':
            case 'Ò':
            changedWord += 'OVER';
                break;
            
            case 'u':
            changedWord += 'ufux';
                break;
            case 'U':
            changedWord += 'UFUX';
                break;
            
            default:
            changedWord += word[i];
                break;
        }
    }

    return changedWord ? key + changedWord : "";
}

export function returnToDefaultVogals( word: string ) {

    let changedWord = word;
    changedWord = 
        changedWord
        .replace(/AIX/gi, 'A')
        .replace(/aix/gi, 'a')

        .replace(/ENDER/gi, 'E')
        .replace(/ender/gi, 'e')

        .replace(/INIX/gi, 'I')
        .replace(/inix/gi, 'i')

        .replace(/OVER/gi, 'O')
        .replace(/over/gi, 'o')
        
        .replace(/UFUX/gi, 'U')
        .replace(/ufux/gi, 'u')

    return changedWord;
}

export function messageToPositiveWords(message: string): string {
    const positiveWords = [
        "Happiness",
        "Joy",
        "Delight",
        "Bliss",
        "Euphoria",
        "Contentment",
        "Satisfaction",
        "Gratitude",
        "Love",
        "Excitement",
        "Enthusiasm",
        "Pleasure",
        "Cheerfulness",
        "Optimism",
        "Hope",
        "Confidence",
        "Serenity",
        "Tranquility",
        "Peace",
        "Harmony",
        "Amusement",
        "Laughter",
        "Smiling",
        "Goodwill",
        "Kindness",
        "Empathy",
        "Compassion",
        "Appreciation",
        "Admiration",
        "Respect",
        "Wonder",
        "Awe",
        "Graciousness",
        "Generosity",
        "Patience",
        "Tenderness",
        "Affection",
        "Warmth",
        "Friendliness",
        "Hospitality",
        "Brave",
        "Daring",
        "Fabulous",
        "Joyful",
        "Kindness",
        "Zealous",
        "Quick",
        "Unique",
        "Excellent",
        "Zeal",
        "Digitalization",
        
    ];

    const alphabeth = "abcdefghijklmnopqrstuvwxyz";
    const lettersToWordsArrayWithThoseLetters = new Map();
    alphabeth.split("").forEach( (letter) => {
        const positiveWordsWithLetter: string[] = [];
        positiveWords.forEach( (word) => {
            if (word.includes(letter)) {
                positiveWordsWithLetter.push(word);
            }
            lettersToWordsArrayWithThoseLetters.set(letter, positiveWordsWithLetter);
        });
    });

    let strToReturn = "";
    message.split("").forEach( (letter) => {
        const lowerCasedLetter = letter.toLowerCase();
        if (alphabeth.includes(lowerCasedLetter)) {
            const wordArray = lettersToWordsArrayWithThoseLetters.get(lowerCasedLetter);
            const randomWordFromWordArray = wordArray[randomIntegerBetweenXandY(0, wordArray.length - 1)];
            const indexOfLetterInWordPlusOne = randomWordFromWordArray.indexOf(lowerCasedLetter) + 1;
            if (indexOfLetterInWordPlusOne === 0) {
                strToReturn += "\n";
            } else if (indexOfLetterInWordPlusOne < 10) {
                strToReturn += " " + indexOfLetterInWordPlusOne + "ª " + randomWordFromWordArray + "\n";
            } else {
                strToReturn += indexOfLetterInWordPlusOne + "ª " + randomWordFromWordArray + "\n";
            }
        } else {
            strToReturn += "\n";
        }
        

        // strToReturn += `${indexOfLetterInWordPlusOne < 10 ? (" " + indexOfLetterInWordPlusOne + "ª") : (indexOfLetterInWordPlusOne) + "ª"} ${randomWordFromWordArray}\n`;
    })

    return strToReturn
}



const reversed_certain_words = [
    "c1g2",
    "e5r4",
    "t1h5",
    "tih5",
    "$$a",
    "eloh$$a",
    "m2a",
    "45a",
    "55a",
    "eloh55a",
    "s_s_a",
    "suloea",
    "eloha",
    "tekcop toh amabala",
    "enilepip naksala",
    "lana",
    "relapmi lana",
    "egakael lana",
    "einnalana",
    "eborplana",
    "xeslana",
    "sugnilina",
    "suna",
    "tihsepa",
    "e5ra",
    "aloera",
    "eloera",
    "naira",
    "esrra",
    "esra",
    "elohesra",
    "nayra",
    "ssa",
    "kcuf ssa",
    "eloh ssa",
    "rekcuf-ssa",
    "tah-ssa",
    "rebbaj-ssa",
    "etarip-ssa",
    "tluassa",
    "gabssa",
    "reggabssa",
    "tidnabssa",
    "gnabssa",
    "degnabssa",
    "regnabssa",
    "sgnabssa",
    "etibssa",
    "retsalbssa",
    "nwolcssa",
    "kcocssa",
    "rekcarcssa",
    "sessa",
    "ecafssa",
    "secafssa",
    "kcufssa",
    "rekcufssa",
    "akkufssa",
    "nilbogssa",
    "el0hssa",
    "tahssa",
    "daehssa",
    "e1ohssa",
    "elohssa",
    "selohssa",
    "reppohssa",
    "erohssa",
    "rekcajssa",
    "yekcojssa",
    "ssikssa",
    "ressikssa",
    "nwolkssa",
    "kcilssa",
    "rekcilssa",
    "revolssa",
    "namssa",
    "retsamssa",
    "yeknomssa",
    "sucumssa",
    "hcnumssa",
    "rehcnumssa",
    "regginssa",
    "rekcapssa",
    "etaripssa",
    "seippupssa",
    "regnarssa",
    "tihsssa",
    "elohsssa",
    "rekcusssa",
    "dawssa",
    "elohwssa",
    "erohwssa",
    "epiwssa",
    "sepiwssa",
    "citore otua",
    "citoreotua",
    "dnuowxa",
    "lezaza",
    "zza",
    "hct!b",
    "sb00b",
    "hc71b",
    "hct1b",
    "ebab",
    "dnalebab",
    "sebab",
    "rettab ybab",
    "eciuj ybab",
    "kcufdab",
    "gag llab",
    "yvarg llab",
    "gnikcik llab",
    "gnikcil llab",
    "kcas llab",
    "gnikcus llab",
    "gabllab",
    "rekcilllab",
    "sllab",
    "kcasllab",
    "topmab",
    "gnab",
    "xob )s'eno( gnab",
    "sorbgnab",
    "regnab",
    "gnignab",
    "kcaberab",
    "lagel ylerab",
    "dekanerab",
    "frab",
    "ecafrab",
    "ecaffrab",
    "dratsab",
    "odratsab",
    "sdratsab",
    "odanitsab",
    "yob yttab",
    "ydwab",
    "sagnozab",
    "smoozab",
    "wbb",
    "msdb",
    "renaeb",
    "srenaeb",
    "malcdedraeb",
    "laitsaeb",
    "ytilaitsaeb",
    "hctaeb",
    "retaeb",
    "taemruoytaeb",
    "revaeb",
    "revaelc revaeb",
    "spil revaeb",
    "niatruc feeb",
    "sniatruc feeb",
    "reeb",
    "hctoyeeb",
    "dnelleb",
    "redneb",
    "hctoeb",
    "laitseb",
    "ytilaitseb",
    "hc+ib",
    "lauxes-ib",
    "hctaib",
    "suoirucib",
    "kcalb gib",
    "stsaerb gib",
    "srekconk gib",
    "stit gib",
    "dratsabgib",
    "ttubgib",
    "reggib",
    "stitgib",
    "obmib",
    "sobmib",
    "tnib",
    "kcoldrib",
    "lauxesib",
    "hctib",
    "tit hctib",
    "ssahctib",
    "dehctib",
    "rehctib",
    "srehctib",
    "sehctib",
    "zehctib",
    "nihctib",
    "gnihctib",
    "stithctib",
    "yhctib",
    "kcoc kcalb",
    "noitca ednolb",
    "noitca ednolb no ednolb",
    "taalcdoolb",
    "ydoolb",
    "lleh ydoolb",
    "wolb",
    "boj wolb",
    "em wolb",
    "dum wolb",
    "daol ruoy wolb",
    "bojwolb",
    "sbojwolb",
    "elffaw eulb",
    "nikpmulb",
    "gnaob",
    "dob",
    "ylidob",
    "nagob",
    "knuhob",
    "kniob",
    "saloiob",
    "kcillob",
    "kcollob",
    "skcollob",
    "kollob",
    "xollob",
    "dmob",
    "egadnob",
    "enob",
    "denob",
    "renob",
    "srenob",
    "gnob",
    "boob",
    "seiboob",
    "sboob",
    "yboob",
    "regoob",
    "eikoob",
    "gnoob",
    "agnoob",
    "sbooob",
    "sboooob",
    "sbooooob",
    "sbooooooob",
    "eetoob",
    "eitoob",
    "ytoob",
    "llac ytoob",
    "ezoob",
    "rezoob",
    "yzoob",
    "mosob",
    "ymosob",
    "lewob",
    "slewob",
    "arb",
    "ereissarb",
    "tsaerb",
    "bojtsaerb",
    "revoltsaerb",
    "namtsaerb",
    "stsaerb",
    "redeerb",
    "rekcufrehtorb",
    "srewohs nworb",
    "noitca ettenurb",
    "atecub",
    "reggub",
    "dereggub",
    "yreggub",
    "ekakkub",
    "tihs llub",
    "parcllub",
    "ekidllub",
    "ekydllub",
    "ebiv tellub",
    "tihsllub",
    "stihsllub",
    "dettihsllub",
    "sdrutllub",
    "mub",
    "yob mub",
    "kcufelbmub",
    "talcmub",
    "kcufmub",
    "remmub",
    "gnub",
    "eloh gnub",
    "agnub",
    "elohgnub",
    "rekcuf ynnub",
    "daol a tsub",
    "ytsub",
    "ekidhctub",
    "ekydhctub",
    "ttub",
    "kcuf ttub",
    "gulp ttub",
    "gnab-ttub",
    "kcuf-ttub",
    "rekcuf-ttub",
    "etarip-ttub",
    "gnabttub",
    "skeehcttub",
    "ecafttub",
    "kcufttub",
    "akcufttub",
    "rekcufttub",
    "daehttub",
    "elohttub",
    "namttub",
    "hcumttub",
    "hcnumttub",
    "rehcnumttub",
    "gulpttub",
    "k-c-0-c",
    "k-c-o-c",
    "t-n-u-c",
    "k.c.0.c",
    ".k.c.o.c",
    "t.n.u.c",
    "kc0c",
    "rekcuskc0c",
    "acac",
    "enohac",
    "eot lemac",
    "eotlemac",
    "lrigmac",
    "tulsmac",
    "erohwmac",
    "rehcnum teprac",
    "rehcnumteprac",
    "kwac",
    "xivrec",
    "elcitsehc",
    "nam ihc-ihc",
    "kcid a htiw kcihc",
    "rekcuf-dlihc",
    "nihc",
    "cnihc",
    "scnihc",
    "knihc",
    "yknihc",
    "daohc",
    "edaohc",
    "eci cohc",
    "sdubesor etalocohc",
    "edohc",
    "sedohc",
    "sgab atohc",
    "apic",
    "krejelcric",
    "t1lc",
    "remaets dnalevelc",
    "xamilc",
    "tilc",
    "rekcil tilc",
    "ecaftilc",
    "kcuftilc",
    "sirotilc",
    "surotilc",
    "stilc",
    "yttilc",
    "rettil yttilc",
    "gowgolc",
    "spmalc revolc",
    "egnulc",
    "kcufretsulc",
    "tunc",
    "niacoc",
    "eniacoc",
    "kcoc",
    "tekcop kcoc",
    "tons kcoc",
    "rekcus kcoc",
    "rekcus-kcoc",
    "ssakcoc",
    "etibkcoc",
    "kcolbkcoc",
    "regrubkcoc",
    "eyekcoc",
    "ecafkcoc",
    "rekcufkcoc",
    "daehkcoc",
    "retslohkcoc",
    "yekcojkcoc",
    "rekconkkcoc",
    "rekonkkcoc",
    "rekcilkcoc",
    "revolkcoc",
    "pmulkcoc",
    "retsamkcoc",
    "relgnomkcoc",
    "leurgnomkcoc",
    "yeknomkcoc",
    "hcnumkcoc",
    "rehcnumkcoc",
    "esonkcoc",
    "teggunkcoc",
    "skcoc",
    "tihskcoc",
    "htimskcoc",
    "ekomskcoc",
    "rekomskcoc",
    "reffinskcoc",
    "recuskcoc",
    "kcuskcoc",
    "dekcuskcoc",
    "rekcuskcoc",
    "srekcuskcoc",
    "gnikcuskcoc",
    "skcuskcoc",
    "akuskcoc",
    "akkuskcoc",
    "elffawkcoc",
    "regdod niffoc",
    "latioc",
    "koc",
    "rehcnumkoc",
    "akcuskoc",
    "eimmoc",
    "modnoc",
    "eihcooc",
    "yhcooc",
    "nooc",
    "ssannooc",
    "snooc",
    "retooc",
    "doow emos poc",
    "aingalorpoc",
    "ailihporpoc",
    "rekcuskroc",
    "elohnroc",
    "erohw proc",
    "xoc",
    "sbarc",
    "kcarc",
    "erohw-kcarc",
    "rekcarc",
    "erohwkcarc",
    "parc",
    "ypparc",
    "eipmaerc",
    "niterc",
    "yekirc",
    "elppirc",
    "ettorc",
    "muc",
    "regguhc muc",
    "retspmud muc",
    "kaerf muc",
    "relzzug muc",
    "elbbubmuc",
    "pmudmuc",
    "retspmudmuc",
    "relzzugmuc",
    "yekcojmuc",
    "remmuc",
    "nimmuc",
    "gnimmuc",
    "smuc",
    "tohsmuc",
    "stohsmuc",
    "tulsmuc",
    "niatsmuc",
    "tratmuc",
    "sugnilinuc",
    "sugnillinuc",
    "nnuc",
    "einnuc",
    "sugnilinnuc",
    "ttnnuc",
    "ynnuc",
    "tnuc",
    "riah tnuc",
    "kcurts-tnuc",
    "ssatnuc",
    "gabtnuc",
    "ecaftnuc",
    "kcuftnuc",
    "rekcuftnuc",
    "elohtnuc",
    "retnuhtnuc",
    "kciltnuc",
    "rekciltnuc",
    "gnikciltnuc",
    "gartnuc",
    "stnuc",
    "elcistnuc",
    "tulstnuc",
    "rekcustnuc",
    "epor tuc",
    "silayc",
    "cufrebyc",
    "kcufrebyc",
    "dekcufrebyc",
    "rekcufrebyc",
    "srekcufrebyc",
    "gnikcufrebyc",
    "xesrebyc",
    "gn0d",
    "3hcu0d",
    "ehcu0d",
    "kc1d",
    "0dl1d",
    "odl1d",
    "ogad",
    "sogad",
    "timmad",
    "nmad",
    "denmad",
    "tinmad",
    "eikrad",
    "nrad",
    "epar etad",
    "eparetad",
    "elyts-eigwad",
    "taorht peed",
    "taorhtpeed",
    "ogged",
    "ailihpordned",
    "kcid",
    "daeh kcid",
    "eloh kcid",
    "yhs kcid",
    "hsi-kcid",
    "ezeens-kcid",
    "gabkcid",
    "sretaebkcid",
    "niarbkcid",
    "reppidkcid",
    "ecafkcid",
    "reppilfkcid",
    "kcufkcid",
    "rekcufkcid",
    "daehkcid",
    "sdaehkcid",
    "elohkcid",
    "hsikcid",
    "eciujkcid",
    "klimkcid",
    "regnomkcid",
    "reppirkcid",
    "skcid",
    "reppiskcid",
    "palskcid",
    "rekcuskcid",
    "gnikcuskcid",
    "relkcitkcid",
    "dawkcid",
    "lesaewkcid",
    "deewkcid",
    "reppihwkcid",
    "dowkcid",
    "reppizkcid",
    "elddid",
    "ekid",
    "odlid",
    "sodlid",
    "fagilid",
    "deewllid",
    "tiwmid",
    "elgnid",
    "seirrebelgnid",
    "yrrebelgnid",
    "knid",
    "sknid",
    "pihspid",
    "tihspid",
    "asrid",
    "ytrid",
    "swollip ytrid",
    "zehcnas ytrid",
    "kcld",
    "elyts god",
    "rekcuf-god",
    "elyts eiggod",
    "elyts-eiggod",
    "elytseiggod",
    "niggod",
    "gniggod",
    "elyts yggod",
    "elyts-yggod",
    "elytsyggod",
    "tteclod",
    "noitanimod",
    "xirtanimod",
    "semmod",
    "gnod",
    "hcnup yeknod",
    "hcnupyeknod",
    "rebbiryeknod",
    "gabhcood",
    "sufood",
    "eikood",
    "hsood",
    "yepod",
    "gnod elbuod",
    "noitartenep elbuod",
    "tfilelbuod",
    "3hcuod",
    "ehcuod",
    "gaf-ehcuod",
    "gabehcuod",
    "sgabehcuod",
    "elffawehcuod",
    "yehcuod",
    "noitca pd",
    "knurd",
    "pmuh yrd",
    "ehcud",
    "ssamud",
    "ssa bmud",
    "ssabmud",
    "sessabmud",
    "tnucbmud",
    "kcufbmud",
    "tihsbmud",
    "ymmud",
    "tihsmud",
    "advd",
    "ekyd",
    "sekyd",
    "kcid a tae",
    "eip riah tae",
    "ssa ym tae",
    "yssuptae",
    "ihcce",
    "etalucaje",
    "detalucaje",
    "setalucaje",
    "gnitalucaje",
    "sgnitalucaje",
    "noitalucaje",
    "etalukaje",
    "tnemegralne",
    "tcere",
    "noitcere",
    "citore",
    "msitore",
    "trocse",
    "eebhosse",
    "hcunue",
    "ycatxe",
    "ysatxe",
    "k c u f",
    "r e k c u f",
    "k-c-u-f",
    "k.c.u.f",
    "ynn4f",
    "k_c_u_f",
    "rekcufecaf",
    "laicaf",
    "kcaf",
    "gaf",
    "gabgaf",
    "rekcufgaf",
    "ggaf",
    "deggaf",
    "gniggaf",
    "tiggaf",
    "ttiggaf",
    "toggaf",
    "kcoctoggaf",
    "stoggaf",
    "sggaf",
    "togaf",
    "stogaf",
    "sgaf",
    "dratgaf",
    "giaf",
    "tgiaf",
    "ynnaf",
    "tidnabynnaf",
    "spalfynnaf",
    "rekcufynnaf",
    "yynaf",
    "traf",
    "rekconktraf",
    "kcuftsaf",
    "taf",
    "ssataf",
    "kcuftaf",
    "rekcuftaf",
    "kucf",
    "rekucf",
    "gnikucf",
    "lacef",
    "kcef",
    "rekcef",
    "hclef",
    "rehclef",
    "gnihclef",
    "etallef",
    "oitallef",
    "hctlef",
    "rehctlef",
    "gnitriuqs elamef",
    "modmef",
    "nainef",
    "gniggif",
    "gnabregnif",
    "kcufregnif",
    "dekcufregnif",
    "rekcufregnif",
    "srekcufregnif",
    "gnikcufregnif",
    "skcufregnif",
    "gniregnif",
    "kcuf tsif",
    "detsif",
    "kcuftsif",
    "dekcuftsif",
    "rekcuftsif",
    "srekcuftsif",
    "gnikcuftsif",
    "sgnikcuftsif",
    "skcuftsif",
    "gnitsif",
    "ytsif",
    "remalf",
    "egnalf",
    "spalf",
    "etulfhself",
    "gol eht golf",
    "yzoolf",
    "daof",
    "haof",
    "eldnof",
    "raboof",
    "koof",
    "rekoof",
    "hsitef toof",
    "kcuftoof",
    "rekcuftoof",
    "bojtoof",
    "rekciltoof",
    "nikserof",
    "kcufkaerf",
    "rekcufykaerf",
    "kcufeerf",
    "xeerf",
    "ggirf",
    "aggirf",
    "gnittorf",
    "rabuf",
    "cuf",
    "kcuf",
    "snottub kcuf",
    "eloh kcuf",
    "ffo kcuf",
    "teppup kcuf",
    "yhport kcuf",
    "amam oy kcuf",
    "uoy kcuf",
    "ssa-kcuf",
    "hctib-kcuf",
    "drat-kcuf",
    "akcuf",
    "ssakcuf",
    "gabkcuf",
    "yobkcuf",
    "niarbkcuf",
    "ttubkcuf",
    "rettubkcuf",
    "dekcuf",
    "pudekcuf",
    "rekcuf",
    "srekcuf",
    "rekcusrekcuf",
    "ecafkcuf",
    "kaerfkcuf",
    "daehkcuf",
    "sdaehkcuf",
    "rehkcuf",
    "elohkcuf",
    "nikcuf",
    "gnikcuf",
    "hctibgnikcuf",
    "sgnikcuf",
    "rekcufrehtomtihsgnikcuf",
    "emkcuf",
    "taemkcuf",
    "drahemkcuf",
    "yeknomkcuf",
    "teggunkcuf",
    "tunkcuf",
    "ttunkcuf",
    "ffokcuf",
    "skcuf",
    "kcitskcuf",
    "dratkcuf",
    "sdratkcuf",
    "tratkcuf",
    "yotkcuf",
    "tawtkcuf",
    "pukcuf",
    "dawkcuf",
    "tihwkcuf",
    "erohwkcuf",
    "tiwkcuf",
    "ttiwkcuf",
    "uoykcuf",
    "rekcap egduf",
    "rekcap-egduf",
    "rekcapegduf",
    "kuf",
    "rekuf",
    "rekkuf",
    "srekkuf",
    "nikkuf",
    "skuf",
    "tihwkuf",
    "tiwkuf",
    "quf",
    "iranatuf",
    "xuf",
    "r0xuf",
    "kcvf",
    "kcxf",
    "tops-g",
    "eag",
    "iag",
    "gnab gnag",
    "gnab-gnag",
    "gnabgnag",
    "degnabgnag",
    "sgnabgnag",
    "ajnag",
    "hsag",
    "ssa yssag",
    "xes yag",
    "ssayag",
    "bobyag",
    "odyag",
    "kcufyag",
    "tsikcufyag",
    "drolyag",
    "syag",
    "xesyag",
    "dratyag",
    "dawyag",
    "redneb redneg",
    "slatineg",
    "yeg",
    "yfg",
    "yahg",
    "yehg",
    "kcoc tnaig",
    "ologig",
    "regnig",
    "oppig",
    "no lrig",
    "pot no lrig",
    "dliw enog slrig",
    "tig",
    "snalg",
    "xctaog",
    "estaog",
    "nmad dog",
    "mad-dog",
    "denmad-dog",
    "nmadog",
    "tinmadog",
    "maddog",
    "timmaddog",
    "nmaddog",
    "denmaddog",
    "tinmaddog",
    "rekcufahtumnmaddog",
    "nmadsdog",
    "nukkog",
    "rewohs nedlog",
    "rewohsnedlog",
    "gowillog",
    "danog",
    "sdanog",
    "aeherronog",
    "lrig oog",
    "hcoog",
    "poopdoog",
    "koog",
    "skoog",
    "msagerog",
    "llehotog",
    "ognirg",
    "eporg",
    "xes puorg",
    "topsg",
    "oftg",
    "odiug",
    "orug",
    "0m0h",
    "om0h",
    "palf mah",
    "boj dnah",
    "bojdnah",
    "eroc drah",
    "no drah",
    "erocdrah",
    "xeserocdrah",
    "ehs-eh",
    "11eh",
    "kcufdaeh",
    "ebeh",
    "beeh",
    "lleh",
    "pmeh",
    "iatneh",
    "nioreh",
    "preh",
    "sepreh",
    "ypreh",
    "ehseh",
    "reltih",
    "vih",
    "oh",
    "raoh",
    "eraoh",
    "gaboh",
    "eoh",
    "reoh",
    "tihs yloh",
    "0moh",
    "yemoh",
    "omoh",
    "tihsbmudomoh",
    "citoreomoh",
    "yeomoh",
    "yeknoh",
    "yknoh",
    "hcooh",
    "hakooh",
    "rekooh",
    "rooh",
    "hctooh",
    "retooh",
    "sretooh",
    "eroh",
    "tseinroh",
    "ynroh",
    "lrac toh",
    "kcihc toh",
    "yssuptoh",
    "xestoh",
    "llik ot woh",
    "pedrum ot woh",
    "redrum ot woh",
    "taf eguh",
    "pmuh",
    "depmuh",
    "gnipmuh",
    "nuh",
    "yssuh",
    "nemyh",
    "pai",
    "pals nairebi",
    "derbni",
    "tsecni",
    "nujni",
    "esruocretni",
    "ff0kr3j",
    "ffo kcaj",
    "ffo-kcaj",
    "ssakcaj",
    "sessakcaj",
    "elohkcaj",
    "ffokcaj",
    "iggaj",
    "ffogaj",
    "tiab liaj",
    "tiabliaj",
    "paj",
    "spaj",
    "tunod yllej",
    "krej",
    "ffo krej",
    "ffo-krej",
    "ff0krej",
    "ssakrej",
    "dekrej",
    "ffokrej",
    "oobagij",
    "oobaggij",
    "oobreggij",
    "msij",
    "zij",
    "mzij",
    "zzij",
    "dezzij",
    "kcoj",
    "sgguj",
    "ynnub elgnuj",
    "ynnubelgnuj",
    "eiknuj",
    "yknuj",
    "rifak",
    "kwak",
    "ekik",
    "sekik",
    "llik",
    "ukabnik",
    "retsknik",
    "yknik",
    "kkk",
    "nalk",
    "bonk",
    "dne bonk",
    "gnibbonk",
    "daebonk",
    "debonk",
    "dnebonk",
    "daehbonk",
    "ykcojbonk",
    "yekojbonk",
    "kcok",
    "mudnok",
    "smudnok",
    "hcook",
    "sehcook",
    "hctook",
    "tuark",
    "muk",
    "remmuk",
    "gnimmuk",
    "smuk",
    "sugnilinuk",
    "ajnuk",
    "tnuk",
    "fiwk",
    "ekyk",
    "hc+i3l",
    "hcti3l",
    "aibal",
    "ssaemal",
    "ssadral",
    "tniartser rehtael",
    "tekcaj thgiarts rehtael",
    "hcel",
    "ytrap nomel",
    "repel",
    "naibsel",
    "snaibsel",
    "obsel",
    "sobsel",
    "zel",
    "naibzel",
    "snaibzel",
    "obzel",
    "sobzel",
    "azzel",
    "eizzel",
    "seizzel",
    "yzzel",
    "oaml",
    "oafml",
    "niol",
    "sniol",
    "atilol",
    "yenool",
    "gnikamevol",
    "ebul",
    "tsul",
    "gnitsul",
    "ytsul",
    "gnikcuf-m",
    "0f0m",
    "of0m",
    "etabret54m",
    "8bret5am",
    "etabret5am",
    "ylgufam",
    "emoc em ekam",
    "gnitriuqs elam",
    "smam",
    "tsihcosam",
    "assam",
    "etab-retsam",
    "8bretsam",
    "tabretsam",
    "3tabretsam",
    "etabretsam",
    "gnitabretsam",
    "noitabretsam",
    "snoitabretsam",
    "etabrutsam",
    "gnitabrutsam",
    "noitabrutsam",
    "ixam",
    "teggafcm",
    "siort a eganem",
    "sesnem",
    "etaurtsnem",
    "noitaurtsnem",
    "htem",
    "kcim",
    "regnif elddim",
    "tegdim",
    "flim",
    "egnim",
    "regnim",
    "noitisop yranoissim",
    "of-om",
    "0fom",
    "ofom",
    "tselom",
    "gnom",
    "oof oof oom oom",
    "eiloom",
    "norom",
    "kcufahtom",
    "akcufahtom",
    "sakcufahtom",
    "zakcufahtom",
    "dekcufahtom",
    "rekcufahtom",
    "srekcufahtom",
    "nikcufahtom",
    "gnikcufahtom",
    "sgnikcufahtom",
    "skcufahtom",
    "rekcuf rehtom",
    "kcufrehtom",
    "akcufrehtom",
    "dekcufrehtom",
    "rekcufrehtom",
    "srekcufrehtom",
    "nikcufrehtom",
    "gnikcufrehtom",
    "sgnikcufrehtom",
    "akkcufrehtom",
    "skcufrehtom",
    "sunev fo dnuom",
    "sdnah rm",
    "rekcufrehtm",
    "rekcufrhtm",
    "gnikcufrhtm",
    "ffum",
    "revid ffum",
    "ffup ffum",
    "revidffum",
    "gnividffum",
    "gnignum",
    "retnum",
    "redrum",
    "ahtum",
    "rekcefahtum",
    "zakcufahtum",
    "rekkcufahtum",
    "rehtum",
    "rekcufrehtum",
    "gnikcufrehtum",
    "gnikcufrhtum",
    "agg1n",
    "regg1n",
    "dan",
    "sdan",
    "dekan",
    "albman",
    "mlapan",
    "yppan",
    "ihsawan",
    "izan",
    "msizan",
    "kcid eht deen",
    "orgen",
    "izanoen",
    "gon gin",
    "gon-gin",
    "oobagin",
    "r3ggin",
    "h4ggin",
    "aggin",
    "haggin",
    "saggin",
    "zaggin",
    "reggin",
    "sreggin",
    "elggin",
    "telgin",
    "ainamohpmin",
    "dormin",
    "ynnin",
    "elppin",
    "selppin",
    "bon",
    "yekoj bon",
    "daehbon",
    "ykcojbon",
    "yekojbon",
    "ecnon",
    "ykoon",
    "segami wfsn",
    "edun",
    "ytidun",
    "stunbmun",
    "rettub tun",
    "kcas tun",
    "kcastun",
    "rettun",
    "ohpmyn",
    "ainamohpmyn",
    "yssupotco",
    "gab dlo",
    "gmo",
    "ihsaromo",
    "slrig owt puc eno",
    "raj eno yug eno",
    "etaipo",
    "muipo",
    "laro",
    "yllaro",
    "nagro",
    "misagro",
    "smisagro",
    "msagro",
    "cimsagro",
    "smsagro",
    "seigro",
    "ygro",
    "yravo",
    "muvo",
    "smuvo",
    ".y.s.s.u.p",
    "nr0p",
    "yddap",
    "elihpodeap",
    "ikap",
    "hcoonap",
    "ysnap",
    "eitnap",
    "seitnap",
    "ytnap",
    "eitsap",
    "ytsap",
    "nwap",
    "pcp",
    "rekcep",
    "daehrekcep",
    "odep",
    "raebodep",
    "elihpodep",
    "ailihpodep",
    "cailihpodep",
    "eep",
    "eepeep",
    "gniggep",
    "etartenep",
    "noitartenep",
    "lainep",
    "elinep",
    "sinep",
    "regnabsinep",
    "rekcufsinep",
    "reffupsinep",
    "noisrevrep",
    "etoyep",
    "illahp",
    "cillahp",
    "xes enohp",
    "xesenohp",
    "kcuhp",
    "kuhp",
    "dekuhp",
    "gnikuhp",
    "dekkuhp",
    "gnikkuhp",
    "skuhp",
    "quhp",
    "tihs fo eceip",
    "rekcufgip",
    "yekip",
    "retibwollip",
    "pmip",
    "sipmip",
    "oknip",
    "ssip",
    "ffo ssip",
    "gip ssip",
    "ffo-ssip",
    "dessip",
    "ffo dessip",
    "ressip",
    "sressip",
    "sessip",
    "spalfssip",
    "nissip",
    "gnissip",
    "ffossip",
    "gipssip",
    "yobyalp",
    "tsehc erusaelp",
    "smp",
    "kcalop",
    "rekoms elop",
    "rekomselop",
    "kcollop",
    "yalpynop",
    "foop",
    "noop",
    "inanoop",
    "ynanoop",
    "gnatnoop",
    "poop",
    "etuhc poop",
    "etuhcpoop",
    "rehcnupoop",
    "yeknom hcrop",
    "yeknomhcrop",
    "nrop",
    "onrop",
    "yhpargonrop",
    "sonrop",
    "top",
    "yttop",
    "kcirp",
    "skcirp",
    "resaetkcirp",
    "girp",
    "gnicreip trebla ecnirp",
    "dorp",
    "norp",
    "etutitsorp",
    "edurp",
    "ohcysp",
    "chtp",
    "ebup",
    "sebup",
    "cibup",
    "sibup",
    "inanup",
    "ynnanup",
    "ynanup",
    "ssaknup",
    "yknup",
    "atnup",
    "ssup",
    "essup",
    "issup",
    "seissup",
    "yssup",
    "traf yssup",
    "ecalap yssup",
    "gnikcilyssup",
    "rednuopyssup",
    "syssup",
    "tsup",
    "otup",
    "faeuq",
    "feeuq",
    "reeuq",
    "tiabreeuq",
    "elohreeuq",
    "oreeuq",
    "sreeuq",
    "ykciuq",
    "miuq",
    "drat-r",
    "ycar",
    "daehgar",
    "renob gnigar",
    "epar",
    "depar",
    "repar",
    "yepar",
    "gnipar",
    "tsipar",
    "hcnuar",
    "latcer",
    "mutcer",
    "sutcer",
    "refeer",
    "drateer",
    "hcier",
    "boner",
    "drater",
    "dedrater",
    "lrigwoc esrever",
    "euver",
    "wajmir",
    "bojmir",
    "gnimmir",
    "dratir",
    "mlap ysor",
    "sretsis 5 reh dna mlap ysor",
    "dratr",
    "hsibbur",
    "mur",
    "pmur",
    "remmarpmur",
    "iksur",
    "enobmort ytsur",
    "tih s",
    "m&s",
    "t-1-h-s",
    "t-i-h-s",
    "b-o-s",
    ".t.i.h.s",
    ".b.o.s",
    "b0s",
    "t_i_h_s",
    "msidas",
    "tsidas",
    "obmas",
    "reggin dnas",
    "rabdnas",
    "reldnas",
    "reggindnas",
    "regnas",
    "murotnas",
    "neeuq egasuas",
    "gacs",
    "ylitnacs",
    "tacs",
    "ozihcs",
    "gnolhcs",
    "gnirossics",
    "wercs",
    "dewercs",
    "gniwercs",
    "taorcs",
    "gorcs",
    "torcs",
    "etorcs",
    "mutorcs",
    "durcs",
    "mucs",
    "namaes",
    "nemaes",
    "ecudes",
    "skes",
    "nemes",
    "xes",
    "oxes",
    "lauxes",
    "yxes",
    "+!hs",
    "t!hs",
    "t1hs",
    "gahs",
    "reggahs",
    "niggahs",
    "gniggahs",
    "emademahs",
    "revaeb devahs",
    "yssup devahs",
    "elamehs",
    "+ihs",
    "irabihs",
    "retfil trihs",
    "tihs",
    "ssa tihs",
    "rekcuf tihs",
    "ssatihs",
    "gabtihs",
    "reggabtihs",
    "pmilbtihs",
    "sniarbtihs",
    "htaerbtihs",
    "dennactihs",
    "tnuctihs",
    "kcidtihs",
    "etihs",
    "retaetihs",
    "detihs",
    "yetihs",
    "ecaftihs",
    "decaftihs",
    "kcuftihs",
    "lluftihs",
    "daehtihs",
    "sdaehtihs",
    "elohtihs",
    "esuohtihs",
    "gnitihs",
    "sgnitihs",
    "stihs",
    "rettipstihs",
    "niatstihs",
    "ttihs",
    "dettihs",
    "rettihs",
    "srettihs",
    "reittihs",
    "tseittihs",
    "gnittihs",
    "sgnittihs",
    "yttihs",
    "zihs",
    "tinzihs",
    "atohs",
    "gnipmirhs",
    "yssis",
    "gaks",
    "knaks",
    "teeks",
    "kcuflluks",
    "gals",
    "eyetnals",
    "evals",
    "ezaels",
    "yzaels",
    "epols",
    "tuls",
    "tekcub tuls",
    "gabtuls",
    "repmudtuls",
    "ssiktuls",
    "stuls",
    "ssatrams",
    "sessatrams",
    "gems",
    "amgems",
    "tums",
    "yttums",
    "hctans",
    "repins",
    "gnillabwons",
    "ffuns",
    "ffo dos",
    "modos",
    "ezimodos",
    "ymodos",
    "hctib a fo nos",
    "taog sselrehtom a fo nos",
    "erohw a fo nos",
    "hctib-a-fo-nos",
    "esuos",
    "desuos",
    "caps",
    "edaps",
    "mreps",
    "cips",
    "kcips",
    "kips",
    "skips",
    "egoolps",
    "esoom egoolps",
    "egoops",
    "koops",
    "sgel daerps",
    "knups",
    "ymaets",
    "ufts",
    "yffits",
    "denots",
    "no parts",
    "noparts",
    "odapparts",
    "pirts",
    "bulc pirts",
    "ekorts",
    "diputs",
    "yggod elyts",
    "kcus",
    "ssakcus",
    "dekcus",
    "gnikcus",
    "skcus",
    "slrig edicius",
    "nemow yrtlus",
    "hctaibafomus",
    "akitsaws",
    "regniws",
    "t1t",
    "5e1tt1t",
    "seitt1t",
    "ffat",
    "giat",
    "evol detniat",
    "ssip eht gnikat",
    "nopmat",
    "drat",
    "trat",
    "ym etsat",
    "yrdwat",
    "gniggab aet",
    "gniggabaet",
    "taet",
    "steet",
    "zeet",
    "dret",
    "etset",
    "eetset",
    "setset",
    "lacitset",
    "elcitset",
    "sitset",
    "emoseerht",
    "gnitaorht",
    "tsurht",
    "guht",
    "tnucrednuht",
    "pu deit",
    "etihw thgit",
    "elknit",
    "tit",
    "knaw tit",
    "kcuftit",
    "itit",
    "seitit",
    "stit",
    "ttit",
    "5eittit",
    "rekcufeittit",
    "seittit",
    "yttit",
    "kcufyttit",
    "rekcufyttit",
    "knawyttit",
    "knawtit",
    "ekot",
    "a ni eugnot",
    "stoot",
    "sselpot",
    "ressot",
    "daehlewot",
    "pmart",
    "ynnart",
    "lauxessnart",
    "yhsart",
    "msidabirt",
    "depmurt",
    "lrig but",
    "lrigbut",
    "drut",
    "hsut",
    "yhsut",
    "t4wt",
    "tawt",
    "daehtawt",
    "spiltawt",
    "stawt",
    "yttawt",
    "elffawtawt",
    "kniwt",
    "eikniwt",
    "sregnif owt",
    "eugnot htiw sregnif owt",
    "puc eno slrig owt",
    "tnuwt",
    "retnuwt",
    "ylgu",
    "rekcufelcnu",
    "seidnu",
    "gnisserdnu",
    "dewnu",
    "trikspu",
    "yalp arhteru",
    "laniru",
    "eniru",
    "ailihporu",
    "suretu",
    "izu",
    "arg41v",
    "arg1v",
    "j-j-av",
    "gav",
    "anigav",
    "yajyajav",
    "muilav",
    "dnuom sunev",
    "elbatqev",
    "argaiv",
    "rotarbiv",
    "dnaw teloiv",
    "nigriv",
    "nexiv",
    "yajyajv",
    "akdov",
    "timov",
    "ailihperarov",
    "rueyov",
    "ragluv",
    "avluv",
    "es00w",
    "daw",
    "gnaw",
    "knaw",
    "reknaw",
    "bojknaw",
    "yknaw",
    "oozaw",
    "eigdew",
    "deew",
    "eineew",
    "eeweew",
    "reniew",
    "odriew",
    "hcnew",
    "maerd tew",
    "kcabtew",
    "er0hw",
    "ecafer0hw",
    "rewop etihw",
    "yetihw",
    "zihw",
    "raohw",
    "suoicilarohw",
    "erohw",
    "suoicilaerohw",
    "gaberohw",
    "derohw",
    "ecaferohw",
    "reppoherohw",
    "esuoherohw",
    "serohw",
    "gnirohw",
    "reggiw",
    "seilliw",
    "ylliw",
    "rekcil wodniw",
    "ssaesiw",
    "sessaesiw",
    "gow",
    "bmow",
    "ydoow",
    "pow",
    "nem gnipparw",
    "hsifrats delknirw",
    "ftw",
    "detar-x",
    "detarx",
    "xx",
    "xxx",
    "ioay",
    "ytsaey",
    "srewohs wolley",
    "diy",
    "yffiy",
    "obboy",
    "elihpooz",
    "ailihpooz",
    "puc 1 slrig 2ailihpooz",
    "bbuz",
    "puc 1 slrig 2",
    "c1g2",
    "e5r4",
    "t1h5",
    "tih5",
    "$$a",
    "eloh$$a",
    "m2a",
    "45a",
    "55a",
    "eloh55a",
    "s_s_a",
    "ailihpomotorca",
    "suloea",
    "eloha",
    "tekcop toh amabala",
    "enilepip naksala",
    "lana",
    "relapmi lana",
    "egakael lana",
    "einnalana",
    "eborplana",
    "xeslana",
    "sugnilina",
    "suna",
    "tihsepa",
    "e5ra",
    "aloera",
    "eloera",
    "naira",
    "esrra",
    "esra",
    "elohesra",
    "nayra",
    "ssa",
    "kcuf ssa",
    "eloh ssa",
    "rekcuf-ssa",
    "tah-ssa",
    "rebbaj-ssa",
    "etarip-ssa",
    "tluassa",
    "gabssa",
    "reggabssa",
    "tidnabssa",
    "gnabssa",
    "degnabssa",
    "regnabssa",
    "sgnabssa",
    "etibssa",
    "retsalbssa",
    "nwolcssa",
    "kcocssa",
    "rekcarcssa",
    "sessa",
    "ecafssa",
    "secafssa",
    "kcufssa",
    "rekcufssa",
    "akkufssa",
    "nilbogssa",
    "el0hssa",
    "tahssa",
    "daehssa",
    "e1ohssa",
    "elohssa",
    "selohssa",
    "reppohssa",
    "erohssa",
    "rekcajssa",
    "yekcojssa",
    "ssikssa",
    "ressikssa",
    "nwolkssa",
    "kcilssa",
    "rekcilssa",
    "revolssa",
    "namssa",
    "retsamssa",
    "yeknomssa",
    "sucumssa",
    "hcnumssa",
    "rehcnumssa",
    "regginssa",
    "rekcapssa",
    "etaripssa",
    "seippupssa",
    "regnarssa",
    "tihsssa",
    "elohsssa",
    "rekcusssa",
    "dawssa",
    "elohwssa",
    "erohwssa",
    "epiwssa",
    "sepiwssa",
    "citore otua",
    "citoreotua",
    "dnuowxa",
    "lezaza",
    "zza",
    "hct!b",
    "sb00b",
    "hc71b",
    "hct1b",
    "ebab",
    "dnalebab",
    "sebab",
    "rettab ybab",
    "eciuj ybab",
    "kcufdab",
    "gag llab",
    "yvarg llab",
    "gnikcik llab",
    "gnikcil llab",
    "kcas llab",
    "gnikcus llab",
    "gabllab",
    "rekcilllab",
    "sllab",
    "kcasllab",
    "topmab",
    "gnab",
    "xob )s'eno( gnab",
    "sorbgnab",
    "regnab",
    "gnignab",
    "kcaberab",
    "lagel ylerab",
    "dekanerab",
    "frab",
    "ecafrab",
    "ecaffrab",
    "dratsab",
    "odratsab",
    "sdratsab",
    "odanitsab",
    "yob yttab",
    "ydwab",
    "sagnozab",
    "smoozab",
    "wbb",
    "msdb",
    "renaeb",
    "srenaeb",
    "malcdedraeb",
    "laitsaeb",
    "ytilaitsaeb",
    "hctaeb",
    "retaeb",
    "taemruoytaeb",
    "revaeb",
    "revaelc revaeb",
    "spil revaeb",
    "niatruc feeb",
    "sniatruc feeb",
    "reeb",
    "hctoyeeb",
    "dnelleb",
    "redneb",
    "hctoeb",
    "laitseb",
    "ytilaitseb",
    "hc+ib",
    "lauxes-ib",
    "hctaib",
    "suoirucib",
    "kcalb gib",
    "stsaerb gib",
    "srekconk gib",
    "stit gib",
    "dratsabgib",
    "ttubgib",
    "reggib",
    "stitgib",
    "obmib",
    "sobmib",
    "tnib",
    "kcoldrib",
    "lauxesib",
    "hctib",
    "tit hctib",
    "ssahctib",
    "dehctib",
    "rehctib",
    "srehctib",
    "sehctib",
    "zehctib",
    "nihctib",
    "gnihctib",
    "stithctib",
    "yhctib",
    "kcoc kcalb",
    "noitca ednolb",
    "noitca ednolb no ednolb",
    "taalcdoolb",
    "ydoolb",
    "lleh ydoolb",
    "wolb",
    "boj wolb",
    "em wolb",
    "dum wolb",
    "daol ruoy wolb",
    "bojwolb",
    "sbojwolb",
    "elffaw eulb",
    "nikpmulb",
    "gnaob",
    "dob",
    "ylidob",
    "nagob",
    "knuhob",
    "kniob",
    "saloiob",
    "kcillob",
    "kcollob",
    "skcollob",
    "kollob",
    "xollob",
    "dmob",
    "egadnob",
    "enob",
    "denob",
    "renob",
    "srenob",
    "gnob",
    "boob",
    "seiboob",
    "sboob",
    "yboob",
    "regoob",
    "eikoob",
    "gnoob",
    "agnoob",
    "sbooob",
    "sboooob",
    "sbooooob",
    "sbooooooob",
    "eetoob",
    "eitoob",
    "ytoob",
    "llac ytoob",
    "ezoob",
    "rezoob",
    "yzoob",
    "mosob",
    "ymosob",
    "lewob",
    "slewob",
    "arb",
    "ereissarb",
    "tsaerb",
    "bojtsaerb",
    "revoltsaerb",
    "namtsaerb",
    "stsaerb",
    "redeerb",
    "rekcufrehtorb",
    "srewohs nworb",
    "noitca ettenurb",
    "atecub",
    "reggub",
    "dereggub",
    "yreggub",
    "ekakkub",
    "tihs llub",
    "parcllub",
    "ekidllub",
    "ekydllub",
    "ebiv tellub",
    "tihsllub",
    "stihsllub",
    "dettihsllub",
    "sdrutllub",
    "mub",
    "yob mub",
    "kcufelbmub",
    "talcmub",
    "kcufmub",
    "remmub",
    "gnub",
    "eloh gnub",
    "agnub",
    "elohgnub",
    "rekcuf ynnub",
    "daol a tsub",
    "ytsub",
    "ekidhctub",
    "ekydhctub",
    "ttub",
    "kcuf ttub",
    "gulp ttub",
    "gnab-ttub",
    "kcuf-ttub",
    "rekcuf-ttub",
    "etarip-ttub",
    "gnabttub",
    "skeehcttub",
    "ecafttub",
    "kcufttub",
    "akcufttub",
    "rekcufttub",
    "daehttub",
    "elohttub",
    "namttub",
    "hcumttub",
    "hcnumttub",
    "rehcnumttub",
    "gulpttub",
    "k-c-0-c",
    "k-c-o-c",
    "t-n-u-c",
    "k.c.0.c",
    ".k.c.o.c",
    "t.n.u.c",
    "kc0c",
    "rekcuskc0c",
    "acac",
    "enohac",
    "eot lemac",
    "eotlemac",
    "lrigmac",
    "tulsmac",
    "erohwmac",
    "rehcnum teprac",
    "rehcnumteprac",
    "kwac",
    "xivrec",
    "elcitsehc",
    "nam ihc-ihc",
    "kcid a htiw kcihc",
    "rekcuf-dlihc",
    "nihc",
    "cnihc",
    "scnihc",
    "knihc",
    "yknihc",
    "daohc",
    "edaohc",
    "eci cohc",
    "sdubesor etalocohc",
    "edohc",
    "sedohc",
    "sgab atohc",
    "apic",
    "krejelcric",
    "t1lc",
    "remaets dnalevelc",
    "xamilc",
    "tilc",
    "rekcil tilc",
    "ecaftilc",
    "kcuftilc",
    "sirotilc",
    "surotilc",
    "stilc",
    "yttilc",
    "rettil yttilc",
    "gowgolc",
    "spmalc revolc",
    "egnulc",
    "kcufretsulc",
    "tunc",
    "niacoc",
    "eniacoc",
    "kcoc",
    "tekcop kcoc",
    "tons kcoc",
    "rekcus kcoc",
    "rekcus-kcoc",
    "ssakcoc",
    "etibkcoc",
    "kcolbkcoc",
    "regrubkcoc",
    "eyekcoc",
    "ecafkcoc",
    "rekcufkcoc",
    "daehkcoc",
    "retslohkcoc",
    "yekcojkcoc",
    "rekconkkcoc",
    "rekonkkcoc",
    "rekcilkcoc",
    "revolkcoc",
    "pmulkcoc",
    "retsamkcoc",
    "relgnomkcoc",
    "leurgnomkcoc",
    "yeknomkcoc",
    "hcnumkcoc",
    "rehcnumkcoc",
    "esonkcoc",
    "teggunkcoc",
    "skcoc",
    "tihskcoc",
    "htimskcoc",
    "ekomskcoc",
    "rekomskcoc",
    "reffinskcoc",
    "recuskcoc",
    "kcuskcoc",
    "dekcuskcoc",
    "rekcuskcoc",
    "srekcuskcoc",
    "gnikcuskcoc",
    "skcuskcoc",
    "akuskcoc",
    "akkuskcoc",
    "elffawkcoc",
    "regdod niffoc",
    "latioc",
    "koc",
    "rehcnumkoc",
    "akcuskoc",
    "eimmoc",
    "modnoc",
    "eihcooc",
    "yhcooc",
    "nooc",
    "ssannooc",
    "snooc",
    "retooc",
    "doow emos poc",
    "aingalorpoc",
    "ailihporpoc",
    "rekcuskroc",
    "elohnroc",
    "erohw proc",
    "xoc",
    "sbarc",
    "kcarc",
    "erohw-kcarc",
    "rekcarc",
    "erohwkcarc",
    "parc",
    "ypparc",
    "eipmaerc",
    "niterc",
    "yekirc",
    "elppirc",
    "ettorc",
    "muc",
    "regguhc muc",
    "retspmud muc",
    "kaerf muc",
    "relzzug muc",
    "elbbubmuc",
    "pmudmuc",
    "retspmudmuc",
    "relzzugmuc",
    "yekcojmuc",
    "remmuc",
    "nimmuc",
    "gnimmuc",
    "smuc",
    "tohsmuc",
    "stohsmuc",
    "tulsmuc",
    "niatsmuc",
    "tratmuc",
    "sugnilinuc",
    "sugnillinuc",
    "nnuc",
    "einnuc",
    "sugnilinnuc",
    "ttnnuc",
    "ynnuc",
    "tnuc",
    "riah tnuc",
    "kcurts-tnuc",
    "ssatnuc",
    "gabtnuc",
    "ecaftnuc",
    "kcuftnuc",
    "rekcuftnuc",
    "elohtnuc",
    "retnuhtnuc",
    "kciltnuc",
    "rekciltnuc",
    "gnikciltnuc",
    "gartnuc",
    "stnuc",
    "elcistnuc",
    "tulstnuc",
    "rekcustnuc",
    "epor tuc",
    "silayc",
    "cufrebyc",
    "kcufrebyc",
    "dekcufrebyc",
    "rekcufrebyc",
    "srekcufrebyc",
    "gnikcufrebyc",
    "xesrebyc",
    "gn0d",
    "3hcu0d",
    "ehcu0d",
    "kc1d",
    "0dl1d",
    "odl1d",
    "ogad",
    "sogad",
    "timmad",
    "nmad",
    "denmad",
    "tinmad",
    "eikrad",
    "nrad",
    "epar etad",
    "eparetad",
    "elyts-eigwad",
    "taorht peed",
    "taorhtpeed",
    "ogged",
    "ailihpordned",
    "kcid",
    "daeh kcid",
    "eloh kcid",
    "yhs kcid",
    "hsi-kcid",
    "ezeens-kcid",
    "gabkcid",
    "sretaebkcid",
    "niarbkcid",
    "reppidkcid",
    "ecafkcid",
    "reppilfkcid",
    "kcufkcid",
    "rekcufkcid",
    "daehkcid",
    "sdaehkcid",
    "elohkcid",
    "hsikcid",
    "eciujkcid",
    "klimkcid",
    " klimkcid",
    "regnomkcid",
    "reppirkcid",
    "skcid",
    "reppiskcid",
    "palskcid",
    "rekcuskcid",
    "gnikcuskcid",
    "relkcitkcid",
    "dawkcid",
    "lesaewkcid",
    "deewkcid",
    "reppihwkcid",
    "dowkcid",
    "reppizkcid",
    "elddid",
    "ekid",
    "odlid",
    "sodlid",
    "fagilid",
    "deewllid",
    "tiwmid",
    "elgnid",
    "seirrebelgnid",
    "yrrebelgnid",
    "knid",
    "sknid",
    "pihspid",
    "tihspid",
    "asrid",
    "ytrid",
    "swollip ytrid",
    "zehcnas ytrid",
    "kcld",
    "elyts god",
    "rekcuf-god",
    "elyts eiggod",
    "elyts-eiggod",
    "elytseiggod",
    "niggod",
    "gniggod",
    "elyts yggod",
    "elyts-yggod",
    "elytsyggod",
    "tteclod",
    "noitanimod",
    "xirtanimod",
    "semmod",
    "gnod",
    "hcnup yeknod",
    "hcnupyeknod",
    "rebbiryeknod",
    "gabhcood",
    "sufood",
    "eikood",
    "hsood",
    "yepod",
    "gnod elbuod",
    "noitartenep elbuod",
    "tfilelbuod",
    "3hcuod",
    "ehcuod",
    "gaf-ehcuod",
    "gabehcuod",
    "sgabehcuod",
    "elffawehcuod",
    "yehcuod",
    "noitca pd",
    "knurd",
    "pmuh yrd",
    "ehcud",
    "ssamud",
    "ssa bmud",
    "ssabmud",
    "sessabmud",
    "tnucbmud",
    "kcufbmud",
    "tihsbmud",
    "ymmud",
    "tihsmud",
    "advd",
    "ekyd",
    "sekyd",
    "kcid a tae",
    "eip riah tae",
    "ssa ym tae",
    "yssuptae",
    "ihcce",
    "etalucaje",
    "detalucaje",
    "setalucaje",
    "gnitalucaje",
    "sgnitalucaje",
    "noitalucaje",
    "etalukaje",
    "tnemegralne",
    "tcere",
    "noitcere",
    "citore",
    "msitore",
    "trocse",
    "eebhosse",
    "hcunue",
    "ycatxe",
    "ysatxe",
    "k c u f",
    "r e k c u f",
    "k-c-u-f",
    "k.c.u.f",
    "ynn4f",
    "k_c_u_f",
    "rekcufecaf",
    "laicaf",
    "kcaf",
    "gaf",
    "gabgaf",
    "rekcufgaf",
    "ggaf",
    "deggaf",
    "gniggaf",
    "tiggaf",
    "ttiggaf",
    "toggaf",
    "kcoctoggaf",
    "stoggaf",
    "sggaf",
    "togaf",
    "stogaf",
    "sgaf",
    "dratgaf",
    "giaf",
    "tgiaf",
    "ynnaf",
    "tidnabynnaf",
    "spalfynnaf",
    "rekcufynnaf",
    "yynaf",
    "traf",
    "rekconktraf",
    "kcuftsaf",
    "taf",
    "ssataf",
    "kcuftaf",
    "rekcuftaf",
    "kucf",
    "rekucf",
    "gnikucf",
    "lacef",
    "kcef",
    "rekcef",
    "hclef",
    "rehclef",
    "gnihclef",
    "etallef",
    "oitallef",
    "hctlef",
    "rehctlef",
    "gnitriuqs elamef",
    "modmef",
    "nainef",
    "gniggif",
    "gnabregnif",
    "kcufregnif",
    "dekcufregnif",
    "rekcufregnif",
    "srekcufregnif",
    "gnikcufregnif",
    "skcufregnif",
    "gniregnif",
    "kcuf tsif",
    "detsif",
    "kcuftsif",
    "dekcuftsif",
    "rekcuftsif",
    "srekcuftsif",
    "gnikcuftsif",
    "sgnikcuftsif",
    "skcuftsif",
    "gnitsif",
    "ytsif",
    "remalf",
    "egnalf",
    "spalf",
    "etulfhself",
    "gol eht golf",
    "yzoolf",
    "daof",
    "haof",
    "eldnof",
    "raboof",
    "koof",
    "rekoof",
    "hsitef toof",
    "kcuftoof",
    "rekcuftoof",
    "bojtoof",
    "rekciltoof",
    "nikserof",
    "kcufkaerf",
    "rekcufykaerf",
    "kcufeerf",
    "xeerf",
    "ggirf",
    "aggirf",
    "gnittorf",
    "rabuf",
    "cuf",
    "kcuf",
    "snottub kcuf",
    "eloh kcuf",
    "ffo kcuf",
    "teppup kcuf",
    "yhport kcuf",
    "amam oy kcuf",
    "uoy kcuf",
    "ssa-kcuf",
    "hctib-kcuf",
    "drat-kcuf",
    "akcuf",
    "ssakcuf",
    "gabkcuf",
    "yobkcuf",
    "niarbkcuf",
    "ttubkcuf",
    "rettubkcuf",
    "dekcuf",
    "pudekcuf",
    "rekcuf",
    "srekcuf",
    "rekcusrekcuf",
    "ecafkcuf",
    "kaerfkcuf",
    "daehkcuf",
    "sdaehkcuf",
    "rehkcuf",
    "elohkcuf",
    "nikcuf",
    "gnikcuf",
    "hctibgnikcuf",
    "sgnikcuf",
    "rekcufrehtomtihsgnikcuf",
    "emkcuf",
    "taemkcuf",
    "drahemkcuf",
    "yeknomkcuf",
    "teggunkcuf",
    "tunkcuf",
    "ttunkcuf",
    "ffokcuf",
    "skcuf",
    "kcitskcuf",
    "dratkcuf",
    "sdratkcuf",
    "tratkcuf",
    "yotkcuf",
    "tawtkcuf",
    "pukcuf",
    "dawkcuf",
    "tihwkcuf",
    "erohwkcuf",
    "tiwkcuf",
    "ttiwkcuf",
    "uoykcuf",
    "rekcap egduf",
    "rekcap-egduf",
    "rekcapegduf",
    "kuf",
    "rekuf",
    "rekkuf",
    "srekkuf",
    "nikkuf",
    "skuf",
    "tihwkuf",
    "tiwkuf",
    "quf",
    "iranatuf",
    "xuf",
    "r0xuf",
    "kcvf",
    "kcxf",
    "tops-g",
    "eag",
    "iag",
    "gnab gnag",
    "gnab-gnag",
    "gnabgnag",
    "degnabgnag",
    "sgnabgnag",
    "ajnag",
    "hsag",
    "ssa yssag",
    "yag",
    "xes yag",
    "ssayag",
    "bobyag",
    "odyag",
    "kcufyag",
    "tsikcufyag",
    "drolyag",
    "syag",
    "xesyag",
    "dratyag",
    "dawyag",
    "redneb redneg",
    "slatineg",
    "yeg",
    "yfg",
    "yahg",
    "yehg",
    "kcoc tnaig",
    "ologig",
    "regnig",
    "oppig",
    "no lrig",
    "pot no lrig",
    "dliw enog slrig",
    "tig",
    "snalg",
    "xctaog",
    "estaog",
    "nmad dog",
    "mad-dog",
    "denmad-dog",
    "nmadog",
    "tinmadog",
    "maddog",
    "timmaddog",
    "nmaddog",
    "denmaddog",
    "tinmaddog",
    "rekcufahtumnmaddog",
    "nmadsdog",
    "nukkog",
    "rewohs nedlog",
    "rewohsnedlog",
    "gowillog",
    "danog",
    "sdanog",
    "aeherronog",
    "lrig oog",
    "hcoog",
    "poopdoog",
    "koog",
    "skoog",
    "msagerog",
    "llehotog",
    "ognirg",
    "eporg",
    "xes puorg",
    "topsg",
    "oftg",
    "odiug",
    "orug",
    "0m0h",
    "om0h",
    "palf mah",
    "boj dnah",
    "bojdnah",
    "eroc drah",
    "no drah",
    "erocdrah",
    "xeserocdrah",
    "ehs-eh",
    "11eh",
    "kcufdaeh",
    "ebeh",
    "beeh",
    "lleh",
    "pmeh",
    "iatneh",
    "nioreh",
    "preh",
    "sepreh",
    "ypreh",
    "ehseh",
    "reltih",
    "vih",
    "oh",
    "raoh",
    "eraoh",
    "gaboh",
    "eoh",
    "reoh",
    "tihs yloh",
    "0moh",
    "yemoh",
    "omoh",
    "tihsbmudomoh",
    "citoreomoh",
    "yeomoh",
    "yeknoh",
    "yknoh",
    "hcooh",
    "hakooh",
    "rekooh",
    "rooh",
    "hctooh",
    "retooh",
    "sretooh",
    "eroh",
    "tseinroh",
    "ynroh",
    "lrac toh",
    "kcihc toh",
    "yssuptoh",
    "xestoh",
    "llik ot woh",
    "pedrum ot woh",
    "redrum ot woh",
    "taf eguh",
    "pmuh",
    "depmuh",
    "gnipmuh",
    "nuh",
    "yssuh",
    "nemyh",
    "pai",
    "pals nairebi",
    "derbni",
    "tsecni",
    "nujni",
    "esruocretni",
    "ff0kr3j",
    "ffO kcaj",
    "ffo kcaj",
    "ffo-kcaj",
    "ssakcaj",
    "sessakcaj",
    "elohkcaj",
    "ffokcaj",
    "iggaj",
    "ffogaj",
    "tiab liaj",
    "tiabliaj",
    "paj",
    "spaj",
    "tunod yllej",
    "krej",
    "ffo krej",
    "ffo-krej",
    "ff0krej",
    "ssakrej",
    "dekrej",
    "ffokrej",
    "oobagij",
    "oobaggij",
    "oobreggij",
    "msij",
    "zij",
    "mzij",
    "zzij",
    "dezzij",
    "kcoj",
    "sgguj",
    "ynnub elgnuj",
    "ynnubelgnuj",
    "eiknuj",
    "yknuj",
    "rifak",
    "kwak",
    "ekik",
    "sekik",
    "llik",
    "ukabnik",
    "retsknik",
    "yknik",
    "kkk",
    "nalk",
    "bonk",
    "dne bonk",
    "gnibbonk",
    "daebonk",
    "debonk",
    "dnebonk",
    "daehbonk",
    "ykcojbonk",
    "yekojbonk",
    "kcok",
    "mudnok",
    "smudnok",
    "hcook",
    "sehcook",
    "hctook",
    "tuark",
    "muk",
    "remmuk",
    "gnimmuk",
    "smuk",
    "sugnilinuk",
    "ajnuk",
    "tnuk",
    "fiwk",
    "ekyk",
    "hc+i3l",
    "hcti3l",
    "aibal",
    "ssaemal",
    "ssadral",
    "tniartser rehtael",
    "tekcaj thgiarts rehtael",
    "hcel",
    "ytrap nomel",
    "repel",
    "naibsel",
    "snaibsel",
    "obsel",
    "sobsel",
    "zel",
    "naibzel",
    "snaibzel",
    "obzel",
    "sobzel",
    "azzel",
    "eizzel",
    "seizzel",
    "yzzel",
    "oaml",
    "oafml",
    "niol",
    "sniol",
    "atilol",
    "yenool",
    "gnikamevol",
    "ebul",
    "tsul",
    "gnitsul",
    "ytsul",
    "gnikcuf-m",
    "0f0m",
    "of0m",
    "etabret54m",
    "8bret5am",
    "etabret5am",
    "ylgufam",
    "emoc em ekam",
    "gnitriuqs elam",
    "smam",
    "tsihcosam",
    "assam",
    "etab-retsam",
    "8bretsam",
    "tabretsam",
    "3tabretsam",
    "etabretsam",
    "gnitabretsam",
    "noitabretsam",
    "snoitabretsam",
    "etabrutsam",
    "gnitabrutsam",
    "noitabrutsam",
    "ixam",
    "teggafcm",
    "siort a eganem",
    "sesnem",
    "etaurtsnem",
    "noitaurtsnem",
    "htem",
    "kcim",
    "regnif elddim",
    "tegdim",
    "flim",
    "egnim",
    "regnim",
    "noitisop yranoissim",
    "of-om",
    "0fom",
    "ofom",
    "tselom",
    "gnom",
    "oof oof oom oom",
    "eiloom",
    "norom",
    "kcufahtom",
    "akcufahtom",
    "sakcufahtom",
    "zakcufahtom",
    "dekcufahtom",
    "rekcufahtom",
    "srekcufahtom",
    "nikcufahtom",
    "gnikcufahtom",
    "sgnikcufahtom",
    "skcufahtom",
    "rekcuf rehtom",
    "kcufrehtom",
    "akcufrehtom",
    "dekcufrehtom",
    "rekcufrehtom",
    "srekcufrehtom",
    "nikcufrehtom",
    "gnikcufrehtom",
    "sgnikcufrehtom",
    "akkcufrehtom",
    "skcufrehtom",
    "sunev fo dnuom",
    "sdnah rm",
    "rekcufrehtm",
    "rekcufrhtm",
    "gnikcufrhtm",
    "ffum",
    "revid ffum",
    "ffup ffum",
    "revidffum",
    "gnividffum",
    "gnignum",
    "retnum",
    "redrum",
    "ahtum",
    "rekcefahtum",
    "zakcufahtum",
    "rekkcufahtum",
    "rehtum",
    "rekcufrehtum",
    "gnikcufrehtum",
    "gnikcufrhtum",
    "agg1n",
    "regg1n",
    "dan",
    "sdan",
    "dekan",
    "albman",
    "mlapan",
    "yppan",
    "ihsawan",
    "izan",
    "msizan",
    "kcid eht deen",
    "orgen",
    "izanoen",
    "gon gin",
    "gon-gin",
    "oobagin",
    "r3ggin",
    "h4ggin",
    "aggin",
    "haggin",
    "saggin",
    "zaggin",
    "reggin",
    "sreggin",
    "elggin",
    "telgin",
    "ainamohpmin",
    "dormin",
    "ynnin",
    "elppin",
    "selppin",
    "bon",
    "yekoj bon",
    "daehbon",
    "ykcojbon",
    "yekojbon",
    "ecnon",
    "ykoon",
    "segami wfsn",
    "edun",
    "ytidun",
    "stunbmun",
    "rettub tun",
    "kcas tun",
    "kcastun",
    "rettun",
    "ohpmyn",
    "ainamohpmyn",
    "yssupotco",
    "gab dlo",
    "gmo",
    "ihsaromo",
    "slrig owt puc eno",
    "raj eno yug eno",
    "etaipo",
    "muipo",
    "laro",
    "yllaro",
    "nagro",
    "misagro",
    "smisagro",
    "msagro",
    "cimsagro",
    "smsagro",
    "seigro",
    "ygro",
    "yravo",
    "muvo",
    "smuvo",
    ".y.s.s.u.p",
    "nr0p",
    "yddap",
    "elihpodeap",
    "ikap",
    "hcoonap",
    "ysnap",
    "eitnap",
    "seitnap",
    "ytnap",
    "eitsap",
    "ytsap",
    "nwap",
    "pcp",
    "rekcep",
    "daehrekcep",
    "odep",
    "raebodep",
    "elihpodep",
    "ailihpodep",
    "cailihpodep",
    "eep",
    "eepeep",
    "gniggep",
    "etartenep",
    "noitartenep",
    "lainep",
    "elinep",
    "sinep",
    "regnabsinep",
    "rekcufsinep",
    "reffupsinep",
    "noisrevrep",
    "etoyep",
    "illahp",
    "cillahp",
    "xes enohp",
    "xesenohp",
    "kcuhp",
    "kuhp",
    "dekuhp",
    "gnikuhp",
    "dekkuhp",
    "gnikkuhp",
    "skuhp",
    "quhp",
    "tihs fo eceip",
    "rekcufgip",
    "yekip",
    "retibwollip",
    "pmip",
    "sipmip",
    "oknip",
    "ssip",
    "ffo ssip",
    "gip ssip",
    "ffo-ssip",
    "dessip",
    "ffo dessip",
    "ressip",
    "sressip",
    "sessip",
    "spalfssip",
    "nissip",
    "gnissip",
    "ffossip",
    "gipssip",
    "yobyalp",
    "tsehc erusaelp",
    "smp",
    "kcalop",
    "rekoms elop",
    "rekomselop",
    "kcollop",
    "yalpynop",
    "foop",
    "noop",
    "inanoop",
    "ynanoop",
    "gnatnoop",
    "poop",
    "etuhc poop",
    "etuhcpoop",
    "rehcnupoop",
    "yeknom hcrop",
    "yeknomhcrop",
    "nrop",
    "onrop",
    "yhpargonrop",
    "sonrop",
    "top",
    "yttop",
    "kcirp",
    "skcirp",
    "resaetkcirp",
    "girp",
    "gnicreip trebla ecnirp",
    "dorp",
    "norp",
    "etutitsorp",
    "edurp",
    "ohcysp",
    "chtp",
    "ebup",
    "sebup",
    "cibup",
    "sibup",
    "inanup",
    "ynnanup",
    "ynanup",
    "ssaknup",
    "yknup",
    "atnup",
    "ssup",
    "essup",
    "issup",
    "seissup",
    "yssup",
    "traf yssup",
    "ecalap yssup",
    "gnikcilyssup",
    "rednuopyssup",
    "syssup",
    "tsup",
    "otup",
    "faeuq",
    "feeuq",
    "reeuq",
    "tiabreeuq",
    "elohreeuq",
    "oreeuq",
    "sreeuq",
    "ykciuq",
    "miuq",
    "drat-r",
    "ycar",
    "daehgar",
    "renob gnigar",
    "epar",
    "depar",
    "repar",
    "yepar",
    "gnipar",
    "tsipar",
    "hcnuar",
    "latcer",
    "mutcer",
    "sutcer",
    "refeer",
    "drateer",
    "hcier",
    "boner",
    "drater",
    "dedrater",
    "lrigwoc esrever",
    "euver",
    "wajmir",
    "bojmir",
    "gnimmir",
    "dratir",
    "mlap ysor",
    "sretsis 5 reh dna mlap ysor",
    "dratr",
    "hsibbur",
    "mur",
    "pmur",
    "remmarpmur",
    "iksur",
    "enobmort ytsur",
    "tih s",
    "m&s",
    "t-1-h-s",
    "t-i-h-s",
    "b-o-s",
    ".t.i.h.s",
    ".b.o.s",
    "b0s",
    "t_i_h_s",
    "msidas",
    "tsidas",
    "obmas",
    "reggin dnas",
    "rabdnas",
    "reldnas",
    "reggindnas",
    "regnas",
    "murotnas",
    "neeuq egasuas",
    "gacs",
    "ylitnacs",
    "tacs",
    "ozihcs",
    "gnolhcs",
    "gnirossics",
    "wercs",
    "dewercs",
    "gniwercs",
    "taorcs",
    "gorcs",
    "torcs",
    "etorcs",
    "mutorcs",
    "durcs",
    "mucs",
    "namaes",
    "nemaes",
    "ecudes",
    "skes",
    "nemes",
    "xes",
    "oxes",
    "lauxes",
    "yxes",
    "+!hs",
    "t!hs",
    "t1hs",
    "gahs",
    "reggahs",
    "niggahs",
    "gniggahs",
    "emademahs",
    "revaeb devahs",
    "yssup devahs",
    "elamehs",
    "+ihs",
    "irabihs",
    "retfil trihs",
    "tihs",
    "ssa tihs",
    "rekcuf tihs",
    "ssatihs",
    "gabtihs",
    "reggabtihs",
    "pmilbtihs",
    "sniarbtihs",
    "htaerbtihs",
    "dennactihs",
    "tnuctihs",
    "kcidtihs",
    "etihs",
    "retaetihs",
    "detihs",
    "yetihs",
    "ecaftihs",
    "decaftihs",
    "kcuftihs",
    "lluftihs",
    "daehtihs",
    "sdaehtihs",
    "elohtihs",
    "esuohtihs",
    "gnitihs",
    "sgnitihs",
    "stihs",
    "rettipstihs",
    "niatstihs",
    "ttihs",
    "dettihs",
    "rettihs",
    "srettihs",
    "reittihs",
    "tseittihs",
    "gnittihs",
    "sgnittihs",
    "yttihs",
    "zihs",
    "tinzihs",
    "atohs",
    "gnipmirhs",
    "yssis",
    "gaks",
    "knaks",
    "teeks",
    "kcuflluks",
    "gals",
    "eyetnals",
    "evals",
    "ezaels",
    "yzaels",
    "epols",
    "tuls",
    "tekcub tuls",
    "gabtuls",
    "repmudtuls",
    "ssiktuls",
    "stuls",
    "ssatrams",
    "sessatrams",
    "gems",
    "amgems",
    "tums",
    "yttums",
    "hctans",
    "repins",
    "gnillabwons",
    "ffuns",
    "ffo dos",
    "modos",
    "ezimodos",
    "ymodos",
    "hctib a fo nos",
    "taog sselrehtom a fo nos",
    "erohw a fo nos",
    "hctib-a-fo-nos",
    "esuos",
    "desuos",
    "caps",
    "edaps",
    "mreps",
    "cips",
    "kcips",
    "kips",
    "skips",
    "egoolps",
    "esoom egoolps",
    "egoops",
    "koops",
    "sgel daerps",
    "knups",
    "ymaets",
    "ufts",
    "yffits",
    "denots",
    "no parts",
    "noparts",
    "odapparts",
    "pirts",
    "bulc pirts",
    "ekorts",
    "diputs",
    "yggod elyts",
    "kcus",
    "ssakcus",
    "dekcus",
    "gnikcus",
    "skcus",
    "slrig edicius",
    "nemow yrtlus",
    "hctaibafomus",
    "akitsaws",
    "regniws",
    "t1t",
    "5e1tt1t",
    "seitt1t",
    "ffat",
    "giat",
    "evol detniat",
    "ssip eht gnikat",
    "nopmat",
    "drat",
    "trat",
    "ym etsat",
    "yrdwat",
    "gniggab aet",
    "gniggabaet",
    "taet",
    "steet",
    "zeet",
    "dret",
    "etset",
    "eetset",
    "setset",
    "lacitset",
    "elcitset",
    "sitset",
    "emoseerht",
    "gnitaorht",
    "tsurht",
    "guht",
    "tnucrednuht",
    "pu deit",
    "etihw thgit",
    "elknit",
    "tit",
    "knaw tit",
    "kcuftit",
    "itit",
    "seitit",
    "stit",
    "ttit",
    "5eittit",
    "rekcufeittit",
    "seittit",
    "yttit",
    "kcufyttit",
    "rekcufyttit",
    "knawyttit",
    "knawtit",
    "ekot",
    "a ni eugnot",
    "stoot",
    "sselpot",
    "ressot",
    "daehlewot",
    "pmart",
    "ynnart",
    "lauxessnart",
    "yhsart",
    "msidabirt",
    "depmurt",
    "lrig but",
    "lrigbut",
    "drut",
    "hsut",
    "yhsut",
    "t4wt",
    "tawt",
    "daehtawt",
    "spiltawt",
    "stawt",
    "yttawt",
    "elffawtawt",
    "kniwt",
    "eikniwt",
    "sregnif owt",
    "eugnot htiw sregnif owt",
    "puc eno slrig owt",
    "tnuwt",
    "retnuwt",
    "ylgu",
    "rekcufelcnu",
    "seidnu",
    "gnisserdnu",
    "dewnu",
    "trikspu",
    "yalp arhteru",
    "laniru",
    "eniru",
    "ailihporu",
    "suretu",
    "izu",
    "arg41v",
    "arg1v",
    "j-j-av",
    "gav",
    "anigav",
    "yajyajav",
    "muilav",
    "dnuom sunev",
    "elbatqev",
    "argaiv",
    "rotarbiv",
    "dnaw teloiv",
    "nigriv",
    "nexiv",
    "yajyajv",
    "akdov",
    "timov",
    "ailihperarov",
    "rueyov",
    "ragluv",
    "avluv",
    "es00w",
    "daw",
    "gnaw",
    "knaw",
    "reknaw",
    "bojknaw",
    "yknaw",
    "oozaw",
    "eigdew",
    "deew",
    "eineew",
    "eeweew",
    "reniew",
    "odriew",
    "hcnew",
    "maerd tew",
    "kcabtew",
    "er0hw",
    "ecafer0hw",
    "rewop etihw",
    "yetihw",
    "zihw",
    "raohw",
    "suoicilarohw",
    "erohw",
    "suoicilaerohw",
    "gaberohw",
    "derohw",
    "ecaferohw",
    "reppoherohw",
    "esuoherohw",
    "serohw",
    "gnirohw",
    "reggiw",
    "seilliw",
    "ylliw",
    "rekcil wodniw",
    "ssaesiw",
    "sessaesiw",
    "gow",
    "bmow",
    "ydoow",
    "pow",
    "nem gnipparw",
    "hsifrats delknirw",
    "ftw",
    "detar-x",
    "detarx",
    "xx",
    "xxx",
    "ioay",
    "ytsaey",
    "srewohs wolley",
    "diy",
    "yffiy",
    "obboy",
    "elihpooz",
    "ailihpooz",
    "bbuz"
];


// const testObj = {};
// reversed_certain_words.forEach((word: string) => {
//     testObj[word] = [];
// });

// const keysWithEmojiTranslationsObj = {
//     "ssa": "🍑",
//     "kcid": "🍆",
//     "hctib": "👩🐶"
// };

// Object.keys(keysWithEmojiTranslationsObj).forEach((key) => {
//     reversed_certain_words[key].push(keysWithEmojiTranslationsObj[key]);
// });

// testObj["ssa"].push("🍑");
// testObj["kcid"].push("🍆");
// testObj["hctib"].push("👩🐶");
// testObj["kcus"].push("👄");
